...
----------------------------------------------------------------------
Ran 3 tests in 0.943s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.517s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.590s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.679s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.647s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.670s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.583s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.604s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.555s

OK
.F.
======================================================================
FAIL: test_add_user (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "unit_test.py", line 35, in test_add_user
    self.assertEqual(UserController.add_user(self.user_1), 'SUCCESS')
AssertionError: 'DUPLICATE' != 'SUCCESS'
- DUPLICATE
+ SUCCESS


----------------------------------------------------------------------
Ran 3 tests in 1.893s

FAILED (failures=1)
...
----------------------------------------------------------------------
Ran 3 tests in 2.473s

OK
